# Utiliser l'image officielle Node.js pour construire l'application
FROM node:18 AS build

# Crée un répertoire de travail dans le conteneur
WORKDIR /app

# Copie les fichiers de configuration npm et Angular
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copie le reste de l'application Angular
COPY . .

# Construire l'application Angular
RUN npm run build --prod

# Étape de production
FROM nginx:alpine

# Copier les fichiers construits de l'image de build Angular dans le dossier de nginx
COPY --from=build /app/dist/event/browser /usr/share/nginx/html

# Copier le fichier de configuration Nginx personnalisé dans le conteneur
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Exposer le port de l'application Angular
EXPOSE 80

# Commande de démarrage du serveur Nginx
CMD ["nginx", "-g", "daemon off;"]
